filter_sets:
    contentblockfullimg:
        filters:
            upscale: { min: [750, 500] }
            thumbnail: { size: [750, 500], mode: outbound }
    contentblockimg:
        filters:
            upscale: { min: [360, 240] }
            thumbnail: { size: [360, 240], mode: outbound }
    fullHD:
        filters:
            upscale: { min: [1920] }
            thumbnail: { size: [1920], mode: outbound }