styleflashere_z_platform_base_homepage:
    path:     /hello/{name}
    defaults: { _controller: StyleflashereZPlatformBaseBundle:Default:index }


styleflasher_ezplatform_base_search:
    path:     /search
    defaults: { _controller: StyleflashereZPlatformBaseBundle:Search:index }
