ezpublish:
    system:
        site_group:
            content_view:
                contentblock:
                    download:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:download.html.twig'
                        match:
                            Identifier\ContentType:
                                - contentblock_download
                    gallery:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:gallery.html.twig'
                        controller: sf.ezp_base.controller.fetch_children:getChildNodesAction
                        match:
                            Identifier\ContentType:
                                - contentblock_gallery
                    textimage:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:textimage.html.twig'
                        match:
                            Identifier\ContentType:
                                - contentblock_text_w_image
                    text:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:text.html.twig'
                        match:
                            Identifier\ContentType:
                                - contentblock_text
                    quicklink:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:quicklink.html.twig'
                        match:
                            Identifier\ContentType:
                                - contentblock_quicklink
                    youtube:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:youtube.html.twig'
                        match:
                            Identifier\ContentType:
                                - contentblock_youtube
                    image:
                        template: 'StyleflashereZPlatformBaseBundle:contentblocks:image.html.twig'
                        match:
                            Identifier\ContentType:
                                - image